### ISSUE TITLE
Cannot build or test a fresh clone

### ISSUE THREAD

**Issue by adamralph** [scriptcs/scriptcs#1260]
I'm intending to send a PR to update to the latest xbehave RC, but I can't build or test a fresh clone.

If I build from the command line, the first problem I have is:

> The system cannot find the path specified.
> 
> *** BUILD FAILED ***

This is because the path to `MSBuild.exe` is hardcoded in build.cmd as `%ProgramFiles(x86)%\MSBuild\15.0\Bin\`, but in a typical VS 2017 installation the path is `%ProgramFiles(x86)%\\Microsoft Visual Studio\2017\{VS edition, e.g. Enterprise}\MSBuild\15.0\Bin`.

If I fix this, I then get

> NuGet.CommandLine.CommandLineException: Failed to load m
  sbuild Toolset ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build, Version=14.0.0
  .0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file spe
  cified.

If I open the solution in VS 2017 and run the tests, I get 22 failures in the `ScriptCs.Tests` project. I've tried using both the VS runner and TestDriven.net. The failure message is the same in each case:

> Test 'ScriptCs.Tests.CSharpScriptEngineTests+TheExecuteMethod.ShouldNotMarkSubmissionsAsIncompleteWhenRunningScript' failed:
> 	System.IO.FileLoadException : Could not load file or assembly 'System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by filipw** [comment]
The binding redirects got inadvertently messed up in #1257, this is fixed in #1261.
The Windows build script has unfortunately been broken for a while now, it's on my TODO list. If you are not constrained by Windows, I recommend using the unix build script for now.

**Comment by filipw** [comment]
This is going to be fixed in #1262

**Comment by BlackFrog1** [comment]
@adamralph try PR #1269 

> === TEST EXECUTION SUMMARY ===
>     ScriptCs.Core.Tests           Total: 231, Errors: 0, Failed:  0, Skipped:  1, Time:  6.214s
>     ScriptCs.Engine.Roslyn.Tests  Total:  28, Errors: 0, Failed:  0, Skipped:  1, Time: 10.463s
>    ScriptCs.Hosting.Tests        Total:  90, Errors: 0, Failed:  0, Skipped:  0, Time:  4.954s
>     ScriptCs.Tests                Total:  45, Errors: 0, Failed:  0, Skipped:  0, Time:  2.850s
>     ScriptCs.Tests.Acceptance     Total: 111, Errors: 0, Failed: 29, Skipped: 39, Time: 53.419s
>                                          ---          -          --           --        -------
>                             GRAND TOTAL: 505          0          29           41        77.901s (88.417s)

> *** BUILD FAILED ***
[build_results.txt](https://github.com/scriptcs/scriptcs/files/1606215/build_results.txt)

**Comment by adamralph** [comment]
@BlackFrog1 those build results indicate a failure.

**Comment by BlackFrog1** [comment]
Those tests have been failing since last year October according TeamCity build log. As @filipw mention above, #1257 broke the binding redirect.  But #1261 & #1263 didn't fix the test.  The test just hasn't ran since last Feb 2017 on the master branch.  Look at the build time in the log below.
![build log 03](https://user-images.githubusercontent.com/550820/34646856-ee15d82e-f340-11e7-9d05-61f32ef280c9.png)

**Comment by filipw** [comment]
This should be fixed by #1262 and #1280.
Also, with #1281 we will run the build on macOS too.

If there are any issues let's reopen this.
